"""удалить user_data из oauth_accounts

Revision ID: 1585fc743f7a
Revises: b5f8518c81d9
Create Date: 2025-01-12 05:09:01.148251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1585fc743f7a'
down_revision: Union[str, None] = 'b5f8518c81d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_oauth_accounts_id'), 'oauth_accounts', ['id'])
    op.drop_column('oauth_accounts', 'user_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('user_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_oauth_accounts_id'), 'oauth_accounts', type_='unique')
    # ### end Alembic commands ###
