"""id и created_at для login_history unique constraint 

Revision ID: 23d502957f40
Revises: 78a42c78960a
Create Date: 2025-01-26 22:10:22.573961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d502957f40'
down_revision: Union[str, None] = '78a42c78960a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_login_history_id_created_at'), 'login_history', ['id', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_login_history_id_created_at'), 'login_history', type_='unique')
    # ### end Alembic commands ###
