"""Партицирование login_history по дате создания

Revision ID: 7cfcadb26933
Revises: 23d502957f40
Create Date: 2025-01-26 22:10:59.728233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cfcadb26933'
down_revision: Union[str, None] = '23d502957f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE login_history DROP CONSTRAINT IF EXISTS unique_id_created_at;")
    op.execute("""
    CREATE TABLE login_history_partitioned (
        id UUID NOT NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        user_id UUID REFERENCES users(id) ON DELETE CASCADE,
        ip_address TEXT NOT NULL,
        user_agent TEXT,
        PRIMARY KEY (id, created_at)
    ) PARTITION BY RANGE (created_at);
    """)
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS login_history_2025_01
        PARTITION OF login_history_partitioned
        FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS login_history_2025_02
        PARTITION OF login_history_partitioned
        FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');
        """
    )
    op.execute(
        """
        INSERT INTO login_history_partitioned (id, created_at, user_id, ip_address, user_agent)
        SELECT id, created_at, user_id, ip_address, user_agent
        FROM login_history;
        """
    )
    op.execute("DROP TABLE IF EXISTS login_history;")
    op.execute("ALTER TABLE login_history_partitioned RENAME TO login_history;")
    op.execute(
        "ALTER TABLE login_history ADD CONSTRAINT unique_id_created_at UNIQUE (id, created_at)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE login_history_singled (
            id UUID NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            user_id UUID REFERENCES users(id) ON DELETE CASCADE,
            ip_address TEXT NOT NULL,
            user_agent TEXT,
            PRIMARY KEY (id, created_at)
        );
        """
    )
    op.execute(
        """
        INSERT INTO login_history_singled (id, created_at, user_id, ip_address, user_agent)
        SELECT id, created_at, user_id, ip_address, user_agent
        FROM login_history;
        """
    )
    op.execute("DROP TABLE IF EXISTS login_history;")
    op.execute("ALTER TABLE login_history_singled RENAME TO login_history;")
    op.execute(
        "ALTER TABLE login_history ADD CONSTRAINT unique_id_created_at UNIQUE (id, created_at)"
    )
    # ### end Alembic commands ###
